### ISSUE TITLE
Sketch freezes

### ISSUE THREAD

**Issue by rubiroid** [mfouquet/Reselect#1]
Hi,

Great plugin! I used it a lot. Until I started to get freezes of the app. After some experiments I find out that because of plugin the number of process threads increased to 2048 and than freezes.

I tried to change number of previous selections to 0 but it didn't help.

**Comment by mfouquet** [comment]
Hello! Glad to hear you like the plugin. That's odd to hear about the freezing. It should be pretty quick with how it handles the selections. Do you have a file you could pass along or some steps to reproduce the problem? Thanks!

**Comment by rubiroid** [comment]
I recorded a video https://youtu.be/NDFvu3qM2vc

**Comment by mfouquet** [comment]
Thanks for the video! That was really helpful. I tried looking at what I have and couldn't figure out what the problem was. Then I looked at the example provided by Sketch (http://developer.sketchapp.com/examples/plugins/selection-changed) and it looks like they have the same problem. I'm going to see if I can lock down what it is specifically and then submit a bug report to them. Thanks again
